id = "g-slowpoke"
name = "Galarian Slowpoke Theme"
version = "0.0.1"
schema_version = 1
authors = ["Gustavo Dias <gustavodiasa2121@gmail.com>"]
description = "A calm, pastel dark theme inspired by Galarian Slowpoke."
repository = "https://github.com/charmingruby/g-slowpoke-zed-theme"
